CREATE TABLE Variables (

Id INT IDENTITY PRIMARY KEY,
Number INT,
String NVARCHAR(100),
Datum DATETIME2 NOT NULL,
Bool BIT CONSTRAINT DefaultValue_Bool DEFAULT 1,
Mail NVARCHAR (225) NOT NULL,
CONSTRAINT CHK_DateColonne CHECK (Datum >= GETDATE()),
CONSTRAINT CHK_MailColonne CHECK (Mail LIKE '%@%.'),
CONSTRAINT CHK_NumberColonne CHECK (Number BETWEEN 0 AND 10)
);